version: '3.1'
services:
  niostreamer:
    image: "niostreamer/niostreamer"
    hostname: "niostreamer"
    ports:
      - "8080:8080"
      - "1935:1935"
    volumes:
      - ./niostreamer.conf:/etc/niostreamer/niostreamer.conf
